namespace ChatBot.Share.DTOs;

/// <summary>
/// Result of evaluating RAG answer quality using NLP metrics + LLM judge.
/// </summary>
public class EvaluationResult
{
    /// <summary>The original question asked.</summary>
    public string Question { get; set; } = string.Empty;

    /// <summary>
    /// Auto-generated reference answer produced by LLM from retrieved chunks.
    /// This is the "ideal answer" the RAG answer is compared against.
    /// </summary>
    public string AutoGeneratedReference { get; set; } = string.Empty;

    /// <summary>The actual answer generated by the RAG pipeline.</summary>
    public string GeneratedAnswer { get; set; } = string.Empty;

    /// <summary>Source documents used to generate the answer.</summary>
    public List<string> SourceDocuments { get; set; } = [];

    /// <summary>BLEU score (0.0–1.0). N-gram precision match vs auto reference.</summary>
    public double BleuScore { get; set; }

    /// <summary>GLEU score (0.0–1.0). Balanced precision+recall vs auto reference.</summary>
    public double GleuScore { get; set; }

    /// <summary>F1 score (0.0–1.0). Token overlap vs auto reference.</summary>
    public double F1Score { get; set; }

    /// <summary>LLM judge score (0.0–1.0). Semantic quality score from LLM.</summary>
    public double LlmJudgeScore { get; set; }

    /// <summary>LLM judge explanation of the score.</summary>
    public string LlmJudgeExplanation { get; set; } = string.Empty;

    /// <summary>Overall average of all four scores.</summary>
    public double OverallScore => (BleuScore + GleuScore + F1Score + LlmJudgeScore) / 4.0;

    /// <summary>Whether an error occurred during evaluation.</summary>
    public bool HasError { get; set; }

    /// <summary>Error message if HasError is true.</summary>
    public string? ErrorMessage { get; set; }
}