using ChatBot.Server.Evaluators;
using ChatBot.Share.DTOs;
using ChatBot.Share.Enums;
using Microsoft.Extensions.AI;
using System.Text;
using System.Text.RegularExpressions;

namespace ChatBot.Server.Services;

/// <summary>
/// Orchestrates the full RAG evaluation pipeline.
///
/// Flow (no reference answer needed from user):
///   1. Hybrid search retrieves top-K chunks for the question
///   2. LLM generates an IDEAL reference answer from those chunks
///   3. LLM generates the actual RAG answer (normal pipeline)
///   4. BLEU, GLEU, F1 compare RAG answer vs LLM-generated reference
///   5. LLM Judge independently scores semantic quality
///   6. Returns all 4 scores + both answers for display
/// </summary>
public class EvaluationService(
    EmbeddingService embeddingService,
    HybridSearchService hybridSearch,
    IChatClient chatClient,
    BLEUEvaluator bleuEvaluator,
    GLEUEvaluator gleuEvaluator,
    F1Evaluator f1Evaluator,
    ILogger<EvaluationService> logger)
{
    public async Task<EvaluationResult> EvaluateAsync(
        EvaluationRequest request,
        CancellationToken cancellationToken = default)
    {
        logger.LogInformation(
            "Starting evaluation — Question: {Q} | DocumentId: {D}",
            request.Question, request.DocumentId);

        var result = new EvaluationResult { Question = request.Question };

        try
        {
            // ── Step 1: Hybrid search — retrieve relevant chunks ───────────
            logger.LogInformation("Step 1: Running hybrid search...");
            var queryEmbedding = await embeddingService.EmbedQueryAsync(request.Question);

            var chunks = await hybridSearch.SearchAsync(
                queryEmbedding,
                request.Question,
                request.TopK,
                request.DocumentId);

            logger.LogInformation("Retrieved {Count} chunks", chunks.Count);

            result.SourceDocuments = chunks
                .Select(c => c.DocumentName)
                .Distinct()
                .ToList();

            if (chunks.Count == 0)
            {
                result.HasError     = true;
                result.ErrorMessage = "No relevant chunks found. Make sure documents are uploaded and Ready.";
                return result;
            }

            // Build shared context string used in both LLM calls
            var context = string.Join("\n\n---\n\n",
                chunks.Select((c, i) =>
                    $"[Source {i + 1}: {c.DocumentName}, Page {c.PageNumber}]\n{c.ChunkText}"));

            // ── Step 2: Auto-generate reference answer from chunks ─────────
            logger.LogInformation("Step 2: Auto-generating reference answer from chunks...");
            result.AutoGeneratedReference = await GenerateReferenceAnswerAsync(
                request.Question, context, cancellationToken);

            logger.LogInformation(
                "Reference answer generated ({Len} chars)", 
                result.AutoGeneratedReference.Length);

            // ── Step 3: Generate actual RAG answer ─────────────────────────
            logger.LogInformation("Step 3: Generating RAG answer...");
            result.GeneratedAnswer = await GenerateRagAnswerAsync(
                request.Question, context, cancellationToken);

            logger.LogInformation(
                "RAG answer generated ({Len} chars)", 
                result.GeneratedAnswer.Length);

            // ── Step 4: NLP metric scores (auto-ref vs RAG answer) ─────────
            logger.LogInformation("Step 4: Computing NLP scores...");
            result.BleuScore = bleuEvaluator.Compute(
                result.GeneratedAnswer, result.AutoGeneratedReference);
            result.GleuScore = gleuEvaluator.Compute(
                result.GeneratedAnswer, result.AutoGeneratedReference);
            result.F1Score   = f1Evaluator.Compute(
                result.GeneratedAnswer, result.AutoGeneratedReference);

            logger.LogInformation(
                "NLP scores — BLEU: {B:F3} GLEU: {G:F3} F1: {F:F3}",
                result.BleuScore, result.GleuScore, result.F1Score);

            // ── Step 5: LLM judge semantic score ──────────────────────────
            logger.LogInformation("Step 5: Running LLM judge...");
            var (judgeScore, judgeExplanation) = await RunLlmJudgeAsync(
                request.Question,
                result.AutoGeneratedReference,
                result.GeneratedAnswer,
                cancellationToken);

            result.LlmJudgeScore       = judgeScore;
            result.LlmJudgeExplanation = judgeExplanation;

            logger.LogInformation(
                "LLM judge score: {S:F3} | Explanation: {E}",
                judgeScore, judgeExplanation);
        }
        catch (Exception ex)
        {
            logger.LogError(ex, "Evaluation failed");
            result.HasError     = true;
            result.ErrorMessage = ex.Message;
        }

        return result;
    }

    // ── Step 2: Auto-generate ideal reference answer from chunks ──────────

    /// <summary>
    /// Asks the LLM to produce the best possible answer based purely on
    /// the retrieved chunks. This becomes the "ground truth" for BLEU/GLEU/F1.
    /// Works for any language — LLM understands Thai, Khmer, English natively.
    /// </summary>
    private async Task<string> GenerateReferenceAnswerAsync(
        string question,
        string context,
        CancellationToken cancellationToken)
    {
        var messages = new List<ChatMessage>
        {
            new(ChatRole.System, """
                You are an expert answer generator. 
                Given document context and a question, produce the most accurate, 
                complete, and concise answer possible using ONLY the provided context.
                This answer will be used as a reference to evaluate other answers.
                Be factual, complete, and clear. Do not add information not in the context.
                """),
            new(ChatRole.User, $"""
                DOCUMENT CONTEXT:
                {context}

                QUESTION: {question}

                Generate the ideal reference answer based solely on the context above.
                """)
        };

        return await CollectStreamAsync(messages, cancellationToken);
    }

    // ── Step 3: Generate actual RAG answer ────────────────────────────────

    private async Task<string> GenerateRagAnswerAsync(
        string question,
        string context,
        CancellationToken cancellationToken)
    {
        var messages = new List<ChatMessage>
        {
            new(ChatRole.System, $"""
                You are a helpful assistant. Answer the user's question based on the 
                document context provided below. Be concise and accurate.

                DOCUMENT CONTEXT:
                {context}
                """),
            new(ChatRole.User, question)
        };

        return await CollectStreamAsync(messages, cancellationToken);
    }

    // ── Step 5: LLM judge ─────────────────────────────────────────────────

    /// <summary>
    /// Asks the LLM to score the RAG answer vs the auto-generated reference.
    /// Works accurately for English, Thai, and Khmer — the LLM understands
    /// all three languages natively, unlike BLEU/GLEU/F1 which use approximations.
    /// </summary>
    private async Task<(double Score, string Explanation)> RunLlmJudgeAsync(
        string question,
        string referenceAnswer,
        string generatedAnswer,
        CancellationToken cancellationToken)
    {
        var messages = new List<ChatMessage>
        {
            new(ChatRole.System,
                "You are a precise evaluator. Always respond in the exact format requested."),
            new(ChatRole.User, $"""
                You are an expert evaluator for question-answering systems.
                Score how well the Generated Answer matches the Reference Answer.

                Question: {question}

                Reference Answer (ideal answer from document): {referenceAnswer}

                Generated Answer (answer to evaluate): {generatedAnswer}

                Evaluate based on:
                1. Factual correctness — does it contain correct facts?
                2. Completeness — does it cover key information from the reference?
                3. Relevance — does it actually answer the question?

                Note: Focus on MEANING and FACTS, not exact wording.
                This works for answers in ANY language (English, Thai, Khmer, etc.)

                Respond in this EXACT format only:
                SCORE: [number from 0 to 10]
                EXPLANATION: [one sentence explaining the score]
                """)
        };

        var response = await CollectStreamAsync(messages, cancellationToken);
        return ParseJudgeResponse(response);
    }

    // ── Helpers ────────────────────────────────────────────────────────────

    private async Task<string> CollectStreamAsync(
        List<ChatMessage> messages,
        CancellationToken cancellationToken)
    {
        var sb = new StringBuilder();
        await foreach (var update in chatClient.GetStreamingResponseAsync(
            messages, cancellationToken: cancellationToken))
        {
            if (!string.IsNullOrEmpty(update.Text))
                sb.Append(update.Text);
        }
        return sb.ToString().Trim();
    }

    private static (double Score, string Explanation) ParseJudgeResponse(string response)
    {
        try
        {
            var scoreMatch = Regex.Match(
                response, @"SCORE:\s*(\d+(?:\.\d+)?)", RegexOptions.IgnoreCase);
            var explanationMatch = Regex.Match(
                response, @"EXPLANATION:\s*(.+?)(?:\n|$)",
                RegexOptions.IgnoreCase | RegexOptions.Singleline);

            double rawScore    = scoreMatch.Success
                ? double.Parse(scoreMatch.Groups[1].Value) : 5.0;
            string explanation = explanationMatch.Success
                ? explanationMatch.Groups[1].Value.Trim()
                : response;

            double normalized = Math.Clamp(rawScore / 10.0, 0.0, 1.0);
            return (normalized, explanation);
        }
        catch
        {
            return (0.5, response.Length > 300 ? response[..300] : response);
        }
    }
}